### 1-Import Important Packages

In [4]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns

### 2-Read Data

In [5]:
netflix=pd.read_csv('Data/netflix_titles.csv')
amazon=pd.read_csv('Data/amazon_prime_titles.csv')
hulu=pd.read_csv('Data/hulu_titles.csv')
dinsey=pd.read_csv('Data/disney_plus_titles.csv')

In [6]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [7]:
amazon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   object
 1   type          9668 non-null   object
 2   title         9668 non-null   object
 3   director      7585 non-null   object
 4   cast          8435 non-null   object
 5   country       672 non-null    object
 6   date_added    155 non-null    object
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   object
 9   duration      9668 non-null   object
 10  listed_in     9668 non-null   object
 11  description   9668 non-null   object
dtypes: int64(1), object(11)
memory usage: 906.5+ KB

In [8]:
hulu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3073 entries, 0 to 3072
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       3073 non-null   object
 1   type          3073 non-null   object
 2   title         3073 non-null   object
 3   director      3 non-null      object
 4   cast          0 non-null      float64
 5   country       1620 non-null   object
 6   date_added    3045 non-null   object
 7   release_year  3073 non-null   int64
 8   rating        2553 non-null   object
 9   duration      2594 non-null   object
 10  listed_in     3073 non-null   object
 11  description   3069 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 288.2+ KB

In [9]:
dinsey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1450 entries, 0 to 1449
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       1450 non-null   object
 1   type          1450 non-null   object
 2   title         1450 non-null   object
 3   director      977 non-null    object
 4   cast          1260 non-null   object
 5   country       1231 non-null   object
 6   date_added    1447 non-null   object
 7   release_year  1450 non-null   int64
 8   rating        1447 non-null   object
 9   duration      1450 non-null   object
 10  listed_in     1450 non-null   object
 11  description   1450 non-null   object
dtypes: int64(1), object(11)
memory usage: 136.1+ KB

### 3.1.1-Netflix Data Understanding

In [10]:
netflix_numeric=netflix[['show_id','duration']]
netflix_categorical=netflix[['type','title','director','cast','country','rating','listed_in','description']]
netflix_datetime=netflix[['date_added','release_year']]

In [11]:
netflix.isna().mean()*100

show_id          0.000000
type             0.000000
title            0.000000
director        29.908028
cast             9.367549
country          9.435676
date_added       0.113546
release_year     0.000000
rating           0.045418
duration         0.034064
listed_in        0.000000
description      0.000000
dtype: float64

### 3.1.2-Netflix Data Cleaning

In [12]:
# netlix dataframe that will be used for analysis
netflix_df=netflix[['type','title','director','cast','country','date_added','release_year','rating','duration','listed_in']]
netflix_df.head()

,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
3,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV"
4,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ..."

In [13]:
# for the director column it is preferable to keep it and replace NaN with N/A
netflix_df.director=np.where(netflix_df.director.isna(),'N/A',netflix_df.director)
netflix_df.director.isna().sum()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_24484\1446079596.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netflix_df.director=np.where(netflix_df.director.isna(),'N/A',netflix_df.director)

np.int64(0)

In [14]:
# for the cast column we don't need all tehse actors we only need the lead and supporting actors
netflix_df[['lead_actor','supporting_actor']]=netflix_df.cast.str.split(', ',regex=True,expand=True).iloc[:,:2]

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_24484\2768989116.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  netflix_df[['lead_actor','supporting_actor']]=netflix_df.cast.str.split(', ',regex=True,expand=True).iloc[:,:2]

In [15]:
# replace actors that are not available with N/A
netflix_df.lead_actor=np.where(netflix_df.lead_actor.isna(),'N/A',netflix_df.lead_actor)
netflix_df.supporting_actor=np.where(netflix_df.supporting_actor.isna(),'N/A',netflix_df.supporting_actor)
netflix_df.drop(columns=['cast'],inplace=True)

In [16]:
netflix_df.head()

,type,title,director,country,date_added,release_year,rating,duration,listed_in,lead_actor,supporting_actor
0,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,N/A,N/A
1,TV Show,Blood & Water,N/A,South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",Ama Qamata,Khosi Ngema
2,TV Show,Ganglands,Julien Leclercq,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",Sami Bouajila,Tracy Gotoas
3,TV Show,Jailbirds New Orleans,N/A,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV",N/A,N/A
4,TV Show,Kota Factory,N/A,India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",Mayur More,Jitendra Kumar

In [17]:
# date_added and release_year should be in datetime format
netflix_df.date_added=pd.to_datetime(netflix_df.date_added.str.strip(),format="%B %d, %Y")
netflix_df.release_year=pd.to_numeric(netflix_df.release_year)

In [18]:
# Drop rows where date_added is not available
netflix_df=netflix_df[netflix_df.date_added.notna()]

In [19]:
# ratings of value_counts
netflix_df.rating.value_counts(dropna=False)

rating
TV-MA       3205
TV-14       2157
TV-PG        861
R            799
PG-13        490
TV-Y7        333
TV-Y         306
PG           287
TV-G         220
NR            79
G             41
TV-Y7-FV       6
NaN            4
NC-17          3
UR             3
66 min         1
74 min         1
84 min         1
Name: count, dtype: int64

In [20]:
netflix_df=netflix_df[netflix_df.rating.str.find('min')==-1]

In [21]:
# duration should be an integer
netflix_df.duration=netflix_df.duration.apply(lambda x:''.join(i for i in str(x) if i.isnumeric()))

In [22]:
netflix_df.duration=pd.to_numeric(netflix_df.duration)

In [23]:
# use mode value for missing values in country
netflix_df.country=netflix_df.country.fillna(netflix_df.country.mode()[0])

In [24]:
netflix_df.reset_index(inplace=True)

In [25]:
netflix_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             8790 non-null   int64
 1   type              8790 non-null   object
 2   title             8790 non-null   object
 3   director          8790 non-null   object
 4   country           8790 non-null   object
 5   date_added        8790 non-null   datetime64[ns]
 6   release_year      8790 non-null   int64
 7   rating            8790 non-null   object
 8   duration          8790 non-null   int64
 9   listed_in         8790 non-null   object
 10  lead_actor        8790 non-null   object
 11  supporting_actor  8790 non-null   object
dtypes: datetime64[ns](1), int64(3), object(8)
memory usage: 824.2+ KB

In [26]:
# netflix movies duration
netflix_df[netflix_df.type=='Movie']['duration'].describe()

count    6126.000000
mean       99.584884
std        28.283225
min         3.000000
25%        87.000000
50%        98.000000
75%       114.000000
max       312.000000
Name: duration, dtype: float64

In [27]:
# netflix TV Shows duration
netflix_df[(netflix_df.type=='TV Show')&(netflix_df.duration>4)]

,index,type,title,director,country,date_added,release_year,rating,duration,listed_in,lead_actor,supporting_actor
8,8,TV Show,The Great British Baking Show,Andy Devonshire,United Kingdom,2021-09-24,2021,TV-14,9,"British TV Shows, Reality TV",Mel Giedroyc,Sue Perkins
21,21,TV Show,Resurrection: Ertugrul,N/A,Turkey,2021-09-22,2018,TV-14,5,"International TV Shows, TV Action & Adventure,...",Engin Altan Düzyatan,Serdar Gökhan
55,55,TV Show,Nailed It,N/A,United States,2021-09-15,2021,TV-PG,6,Reality TV,Nicole Byer,Jacques Torres
65,65,TV Show,Numberblocks,N/A,United Kingdom,2021-09-15,2021,TV-Y,6,Kids' TV,Beth Chalmers,David Holt
67,67,TV Show,Saved by the Bell,N/A,United States,2021-09-15,1994,TV-PG,9,"Kids' TV, TV Comedies",Mark-Paul Gosselaar,Tiffani Thiessen
...,...,...,...,...,...,...,...,...,...,...,...,...
8405,8422,TV Show,The Mind of a Chef,N/A,United States,2017-11-01,2016,TV-PG,5,Docuseries,Anthony Bourdain,David Chang
8425,8442,TV Show,The Office (U.S.),N/A,United States,2016-01-01,2012,TV-14,9,TV Comedies,Steve Carell,John Krasinski
8540,8557,TV Show,The West Wing,N/A,United States,2015-12-25,2005,TV-14,7,TV Dramas,Martin Sheen,Rob Lowe
8693,8710,TV Show,Weeds,N/A,United States,2014-04-01,2012,TV-MA,8,"TV Comedies, TV Dramas",Mary-Louise Parker,Hunter Parrish
8709,8726,TV Show,When Calls the Heart,N/A,United States,2018-12-29,2017,TV-PG,5,TV Dramas,Erin Krakow,Daniel Lissing

In [28]:
netflix_df.drop_duplicates(inplace=True)

### 3.1.3-Netflix EDA

In [29]:
# Ratio of Movies to TV Shows
px.pie(netflix_df.groupby(by='type')['title'].count(),
       names=netflix_df.groupby(by='type')['title'].count().index,
       values=netflix_df.groupby(by='type')['title'].count().values,
       color_discrete_sequence=['#221f1f', '#b20710'],)

In [30]:
# listed_in columns has masny categories so we will use get dummies
px.bar_polar(r=netflix_df[netflix_df.type=='Movie']['listed_in'].str.get_dummies(sep=', ').sum().drop(index="Movies").values,
             theta=netflix_df[netflix_df.type=='Movie']['listed_in'].str.get_dummies(sep=', ').sum().drop(index="Movies").index,
             color_discrete_sequence=['#221f1f'])

In [31]:
# listed_in columns has masny categories so we will use get dummies
px.bar_polar(r=netflix_df[netflix_df.type=='TV Show']['listed_in'].str.get_dummies(sep=', ').sum().drop(index="TV Shows").values,
             theta=netflix_df[netflix_df.type=='TV Show']['listed_in'].str.get_dummies(sep=', ').sum().drop(index="TV Shows").index,
             color_discrete_sequence=['#b20710', '#e50914','#f5f5f1'],)

In [32]:
# Movies release through time
px.bar(data_frame=netflix_df[netflix_df.type=='Movie'].groupby(by='release_year')['title'].count(),
       x=netflix_df[netflix_df.type=='Movie'].groupby(by='release_year')['title'].count().index,
       y=netflix_df[netflix_df.type=='Movie'].groupby(by='release_year')['title'].count().values,
       color_discrete_sequence=['#221f1f'])

In [33]:
# TV Shows release through time
px.bar(data_frame=netflix_df[netflix_df.type=='TV Show'].groupby(by='release_year')['title'].count(),
       x=netflix_df[netflix_df.type=='TV Show'].groupby(by='release_year')['title'].count().index,
       y=netflix_df[netflix_df.type=='TV Show'].groupby(by='release_year')['title'].count().values,
       color_discrete_sequence=['#221f1f'])

Most of movies and TV shows were released during the pandemic

In [34]:
px.bar(data_frame=netflix_df.country.str.rstrip(',').str.get_dummies(sep=', ').sum().sort_values(ascending=False)[:10],
       x=netflix_df.country.str.rstrip(',').str.get_dummies(sep=', ').sum().sort_values(ascending=False)[:10].index,
       y=netflix_df.country.str.rstrip(',').str.get_dummies(sep=', ').sum().sort_values(ascending=False)[:10].values,
       title='Top 10 Countries on Netflix',
       color_discrete_sequence=['#e50914'])

In [35]:
# Movies and TV Shows split by country
x_total=netflix_df.country.str.rstrip(',').str.get_dummies(sep=', ').sum().sort_values(ascending=False).to_frame().reset_index()
x_total.columns=['Country', 'Total']
x_total.head()
x_movies=netflix_df[netflix_df.type=='Movie']['country'].str.rstrip(',').str.get_dummies(sep=', ').sum().sort_values(ascending=False).to_frame().reset_index()
x_movies.columns=['Country', 'Movies']
x_movies.head()
x_shows=netflix_df[netflix_df.type=='TV Show']['country'].str.rstrip(',').str.get_dummies(sep=', ').sum().sort_values(ascending=False).to_frame().reset_index()
x_shows.columns=['Country', 'Shows']
x_shows.head()
x_total=x_total.merge(x_movies,how='inner',on=['Country'])
x_total=x_total.merge(x_shows,how='inner',on=['Country'])
x_total.head()

          Country  Total  Movies  Shows
0   United States   4510    3188   1322
1           India   1046     962     84
2  United Kingdom    805     534    271
3          Canada    445     319    126
4          France    393     303     90

In [36]:
px.bar(data_frame=x_total[:11],
       y='Country',
       x=['Movies','Shows'],
       barmode='stack',
       color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])

Almost all top countries watch movies more than TV shows except for South Korea and Japan which have more TV Shows than movies

In [37]:
# Rating Distribution for each type
y=data_frame=netflix_df.groupby(by=['type','rating'])['title'].count().to_frame().reset_index()
y.head()
px.sunburst(data_frame=y,
            path=['type','rating'],
            values='title',
            title='Netflix Ratings',
            color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])

In [38]:
mask = {
    'TV-PG': 'Older Kids',
    'TV-MA': 'Adults',
    'TV-Y7-FV': 'Older Kids',
    'TV-Y7': 'Older Kids',
    'TV-14': 'Teens',
    'R': 'Adults',
    'TV-Y': 'Kids',
    'NR': 'Adults',
    'PG-13': 'Teens',
    'TV-G': 'Kids',
    'PG': 'Older Kids',
    'G': 'Kids',
    'UR': 'Adults',
    'NC-17': 'Adults'
}
z=netflix_df.groupby(by=['type',netflix_df.rating.map(mask)])['title'].count().to_frame().reset_index()
px.sunburst(data_frame=z,
            path=['type','rating'],
            values='title',
            title='Netflix Ratings',
            color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])

In [39]:
px.pie(data_frame=netflix_df[netflix_df.country.str.contains('United States')].groupby(by=netflix_df.rating.map(mask))['title'].count().to_frame().reset_index(),
       names='rating',
       values='title',
       title='USA Netflix ratings distribution',
       color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])

In [40]:
px.pie(data_frame=netflix_df[netflix_df.country.str.contains('Egypt')].groupby(by=netflix_df.rating.map(mask))['title'].count().to_frame().reset_index(),
       names='rating',
       values='title',
       title='Egypt Netflix ratings distribution',
       color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])

In [41]:
# When does Netflix releases most of its content during the year
px.area(data_frame=netflix_df.groupby(by=netflix_df['date_added'].dt.month_name())['title'].count().sort_values(ascending=False),
        x=netflix_df.groupby(by=netflix_df['date_added'].dt.month_name())['title'].count().sort_values(ascending=False).index,
        y=netflix_df.groupby(by=netflix_df['date_added'].dt.month_name())['title'].count().sort_values(ascending=False).values,
        title='Netflix releases distributed across the year',
        color_discrete_sequence=['#b20710'])

In [43]:
netflix_df.to_csv('netflix_cleaned.csv',index=False)

In [13]:
netflix_df[(netflix_df.country.str.contains('Egypt'))&(netflix_df.type=='Movie')].groupby('lead_actor').count()

NameError: name 'netflix_df' is not defined

### 3.1.4-Netflix Deployment

In [30]:
%%writefile app.py
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns

df = pd.read_csv('netflix_cleaned.csv')
df['date_added'] = pd.to_datetime(df['date_added'])
df['duration'] = pd.to_numeric(df['duration'])

st.set_page_config(page_title='Netflix Dashboard', layout='wide')

selected_type = st.sidebar.selectbox('Type', options=['Movie', 'TV Show'])

# min_year = int(df[df.type==selected_type]['release_year'].min())
# max_year = int(df[df.type==selected_type]['release_year'].max())
# year_range = st.sidebar.slider('Year range', min_year, max_year, (min_year, max_year))

all_countries=df.country.str.rstrip(',').str.get_dummies(sep=', ').columns
selected_country=st.sidebar.selectbox('country',options=all_countries)

# if selected_type=='Movie':
#     all_genres=df[df.type==selected_type]['listed_in'].str.get_dummies(sep=', ').drop(columns=['Movies']).columns
# else:
#     all_genres=df[df.type==selected_type]['listed_in'].str.get_dummies(sep=', ').drop(columns=['TV Shows']).columns
# selected_genre=st.sidebar.selectbox('genre',options=all_genres)

filtered_df=df[(df.type==selected_type)&(df.country.str.contains(selected_country))]

tab1,tab2=st.tabs(['overview','plots'])
with tab1:
    st.dataframe(filtered_df[['title','director','rating','lead_actor','supporting_actor']])
    col1,col2,col3=st.columns(3)
    col1.metric('number of titles',len(filtered_df))
    col2.metric('number of directors',filtered_df[filtered_df.director!='N/A']['director'].nunique())
    col3.metric('average duration',round(number=filtered_df['duration'].mean(),ndigits=0))
with tab2:
    col1, col2 = st.columns(2)

    top_genres=filtered_df['listed_in'].str.rstrip(',').str.get_dummies(sep=', ').sum().to_frame(name='Titles').reset_index().head()
    top_genres.columns=['Genre','Titles']
    fig1=px.pie(data_frame=top_genres,names='Genre',values='Titles',color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])
    
    top_lead=filtered_df.groupby('lead_actor')['title'].count().sort_values(ascending=False).head(5).reset_index()
    top_lead.columns = ['Actor', 'Appearances']
    fig2=px.bar(top_lead,x='Appearances',y='Actor',title='Top 5 Lead Actors',orientation='h',color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])

    mask = {
    'TV-PG': 'Older Kids',
    'TV-MA': 'Adults',
    'TV-Y7-FV': 'Older Kids',
    'TV-Y7': 'Older Kids',
    'TV-14': 'Teens',
    'R': 'Adults',
    'TV-Y': 'Kids',
    'NR': 'Adults',
    'PG-13': 'Teens',
    'TV-G': 'Kids',
    'PG': 'Older Kids',
    'G': 'Kids',
    'UR': 'Adults',
    'NC-17': 'Adults'
    }
    top_ratings=filtered_df.groupby(filtered_df.rating.map(mask))['title'].count().reset_index()
    top_ratings.columns=['Rating','Titles']
    fig3=px.pie(data_frame=top_ratings,names='Rating',values='Titles',color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])

    top_supprt=filtered_df.groupby('supporting_actor')['title'].count().sort_values(ascending=False).head(5).reset_index()
    top_supprt.columns = ['Actor', 'Appearances']
    fig4=px.bar(top_supprt,x='Appearances',y='Actor',title='Top 5 Supporting Actors',orientation='h',color_discrete_sequence=['#221f1f', '#b20710', '#e50914','#f5f5f1'])

    with col1:
        st.plotly_chart(fig1, use_container_width=True)
        st.plotly_chart(fig3, use_container_width=True)
    
    with col2:
        st.plotly_chart(fig2, use_container_width=True)
        st.plotly_chart(fig4, use_container_width=True)

Overwriting app.py

In [8]:
! streamlit run app.py

^C